# Generated by Django 6.0 on 2025-12-14 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
                ('inn', models.CharField(blank=True, max_length=12, null=True)),
                ('bik', models.CharField(blank=True, max_length=12, null=True)),
                ('nomer_korrespondentnogo_scheta', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Dolzhnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dolzhnost',
            },
        ),
        migrations.CreateModel(
            name='EdinitsaIzmereniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'edinitsa_izmereniya',
            },
        ),
        migrations.CreateModel(
            name='Gorod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gorod',
            },
        ),
        migrations.CreateModel(
            name='GruppaTovarov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'gruppa_tovarov',
            },
        ),
        migrations.CreateModel(
            name='Klassifikaciya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'klassifikaciya',
            },
        ),
        migrations.CreateModel(
            name='Professiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'professiya',
            },
        ),
        migrations.CreateModel(
            name='Specialnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'specialnost',
            },
        ),
        migrations.CreateModel(
            name='Strana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'strana',
            },
        ),
        migrations.CreateModel(
            name='StruktPodrazdelenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'strukt_podrazdelenie',
            },
        ),
        migrations.CreateModel(
            name='Ulitsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ulitsa',
            },
        ),
        migrations.CreateModel(
            name='Vyruchka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolichestvo', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vyruchka',
            },
        ),
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
                ('familiya_direktora', models.CharField(blank=True, max_length=25, null=True)),
                ('imya_direktora', models.CharField(blank=True, max_length=25, null=True)),
                ('otchestvo_direktora', models.CharField(blank=True, max_length=25, null=True)),
                ('id_gorod', models.ForeignKey(blank=True, db_column='id_gorod', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gorod')),
                ('id_strana', models.ForeignKey(blank=True, db_column='id_strana', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.strana')),
                ('id_ulica', models.ForeignKey(blank=True, db_column='id_ulica', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ulitsa')),
            ],
            options={
                'db_table': 'magazin',
            },
        ),
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(blank=True, max_length=50, null=True)),
                ('id_gruppa_tovarov', models.ForeignKey(db_column='id_gruppa_tovarov', on_delete=django.db.models.deletion.PROTECT, to='core.gruppatovarov')),
            ],
            options={
                'db_table': 'otdel',
            },
        ),
        migrations.CreateModel(
            name='Postavshchik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
                ('kod_po_ok', models.CharField(blank=True, max_length=20, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=15, null=True)),
                ('nomer_raschetnogo_scheta', models.CharField(blank=True, max_length=25, null=True)),
                ('familiya_rukovoditelya', models.CharField(blank=True, max_length=25, null=True)),
                ('imya_rukovoditelya', models.CharField(blank=True, max_length=25, null=True)),
                ('otchestvo_rukovoditelya', models.CharField(blank=True, max_length=25, null=True)),
                ('nomer_telefona', models.CharField(blank=True, max_length=25, null=True)),
                ('nomer_doma', models.CharField(blank=True, max_length=25, null=True)),
                ('id_bank', models.ForeignKey(blank=True, db_column='id_bank', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bank')),
                ('id_gorod', models.ForeignKey(blank=True, db_column='id_gorod', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gorod')),
                ('id_strana', models.ForeignKey(blank=True, db_column='id_strana', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.strana')),
                ('id_ulica', models.ForeignKey(blank=True, db_column='id_ulica', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ulitsa')),
            ],
            options={
                'db_table': 'postavshchik',
            },
        ),
        migrations.CreateModel(
            name='Rabotnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(blank=True, max_length=25, null=True)),
                ('imya', models.CharField(blank=True, max_length=25, null=True)),
                ('otchestvo', models.CharField(blank=True, max_length=25, null=True)),
                ('data_rozhdeniya', models.DateField(blank=True, null=True)),
                ('nomer_doma', models.CharField(blank=True, max_length=5, null=True)),
                ('trudovoy_stazh', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pol', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True)),
                ('id_dolzhnost', models.ForeignKey(blank=True, db_column='id_dolzhnost', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.dolzhnost')),
                ('id_gorod', models.ForeignKey(blank=True, db_column='id_gorod', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gorod')),
                ('id_otdela', models.ForeignKey(blank=True, db_column='id_otdela', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.otdel')),
                ('id_strana', models.ForeignKey(blank=True, db_column='id_strana', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.strana')),
                ('id_ulica', models.ForeignKey(blank=True, db_column='id_ulica', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ulitsa')),
            ],
            options={
                'db_table': 'rabotnik',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=25)),
                ('kolichestvo_na_sklade', models.IntegerField(blank=True, null=True)),
                ('cena_postavki', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cena_prodazhi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_edinitsa_izmereniya', models.ForeignKey(blank=True, db_column='id_edinitsa_izmereniya', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.edinitsaizmereniya')),
                ('id_gruppa_tovarov', models.ForeignKey(blank=True, db_column='id_gruppa_tovarov', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gruppatovarov')),
            ],
            options={
                'db_table': 'tovar',
            },
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_postavki', models.DateField(blank=True, null=True)),
                ('kolichestvo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('id_postavshchik', models.ForeignKey(db_column='id_postavshchik', on_delete=django.db.models.deletion.PROTECT, to='core.postavshchik')),
                ('id_tovar', models.ForeignKey(db_column='id_tovar', on_delete=django.db.models.deletion.PROTECT, to='core.tovar')),
            ],
            options={
                'db_table': 'postavka',
            },
        ),
        migrations.CreateModel(
            name='MagazinTovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_magazin', models.ForeignKey(db_column='id_magazin', on_delete=django.db.models.deletion.PROTECT, to='core.magazin')),
                ('id_tovar', models.ForeignKey(db_column='id_tovar', on_delete=django.db.models.deletion.PROTECT, to='core.tovar')),
            ],
            options={
                'db_table': 'magazin_tovar',
            },
        ),
        migrations.CreateModel(
            name='MestoRaboty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(blank=True, max_length=50, null=True)),
                ('nomer_doma', models.CharField(blank=True, max_length=10, null=True)),
                ('id_gorod', models.ForeignKey(blank=True, db_column='id_gorod', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gorod')),
                ('id_strana', models.ForeignKey(blank=True, db_column='id_strana', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.strana')),
                ('id_ulica', models.ForeignKey(blank=True, db_column='id_ulica', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ulitsa')),
            ],
            options={
                'db_table': 'mesto_raboty',
            },
        ),
        migrations.CreateModel(
            name='TovarVyruchka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolichestvo', models.IntegerField(blank=True, null=True)),
                ('id_tovar', models.ForeignKey(db_column='id_tovar', on_delete=django.db.models.deletion.PROTECT, to='core.tovar')),
                ('id_vyruchka', models.ForeignKey(db_column='id_vyruchka', on_delete=django.db.models.deletion.PROTECT, to='core.vyruchka')),
            ],
            options={
                'db_table': 'tovar_vyruchka',
            },
        ),
        migrations.CreateModel(
            name='RabotnikVyruchka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rabotnik', models.ForeignKey(db_column='id_rabotnik', on_delete=django.db.models.deletion.PROTECT, to='core.rabotnik')),
                ('id_vyruchka', models.ForeignKey(db_column='id_vyruchka', on_delete=django.db.models.deletion.PROTECT, to='core.vyruchka')),
            ],
            options={
                'db_table': 'rabotnik_vyruchka',
            },
        ),
        migrations.CreateModel(
            name='ZapisiTrudKnizhke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_priema_na_rabotu', models.DateField(blank=True, null=True)),
                ('data_uvolenija', models.DateField(blank=True, null=True)),
                ('vid_meropriyatiya', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('prichina_prekrashcheniya_tr', models.TextField(blank=True, null=True)),
                ('nomer', models.CharField(blank=True, max_length=10, null=True)),
                ('vid_dokumenta', models.CharField(blank=True, choices=[('Прием', 'Прием'), ('Увольнение', 'Увольнение'), ('Перевод', 'Перевод')], max_length=10, null=True)),
                ('id_dolzhnosti', models.ForeignKey(db_column='id_dolzhnosti', on_delete=django.db.models.deletion.PROTECT, to='core.dolzhnost')),
                ('id_klassifikacii', models.ForeignKey(db_column='id_klassifikacii', on_delete=django.db.models.deletion.PROTECT, to='core.klassifikaciya')),
                ('id_mesto_raboty', models.ForeignKey(db_column='id_mesto_raboty', on_delete=django.db.models.deletion.PROTECT, to='core.mestoraboty')),
                ('id_professii', models.ForeignKey(db_column='id_professii', on_delete=django.db.models.deletion.PROTECT, to='core.professiya')),
                ('id_rabotnika', models.ForeignKey(db_column='id_rabotnika', on_delete=django.db.models.deletion.PROTECT, to='core.rabotnik')),
                ('id_specialnosti', models.ForeignKey(db_column='id_specialnosti', on_delete=django.db.models.deletion.PROTECT, to='core.specialnost')),
                ('id_strukturnoe_podrazdelenie', models.ForeignKey(db_column='id_strukturnoe_podrazdelenie', on_delete=django.db.models.deletion.PROTECT, to='core.struktpodrazdelenie')),
            ],
            options={
                'db_table': 'zapisi_trud_knizhke',
            },
        ),
        migrations.AddConstraint(
            model_name='rabotnik',
            constraint=models.CheckConstraint(condition=models.Q(('pol__in', ['Мужской', 'Женский']), ('pol__isnull', True), _connector='OR'), name='rabotnik_pol_check'),
        ),
        migrations.AddConstraint(
            model_name='zapisitrudknizhke',
            constraint=models.CheckConstraint(condition=models.Q(('vid_dokumenta__in', ['Прием', 'Увольнение', 'Перевод']), ('vid_dokumenta__isnull', True), _connector='OR'), name='zapisi_vid_dokumenta_check'),
        ),
    ]
