# Generated by Django 6.0 on 2025-12-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vyruchka',
            name='kolichestvo',
        ),
        migrations.AddField(
            model_name='magazintovar',
            name='kolichestvo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otdel',
            name='id_magazin',
            field=models.ForeignKey(blank=True, db_column='id_magazin', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.magazin'),
        ),
        migrations.AddField(
            model_name='tovarvyruchka',
            name='cena_prodazhi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tovarvyruchka',
            name='summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vyruchka',
            name='id_magazin',
            field=models.ForeignKey(blank=True, db_column='id_magazin', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.magazin'),
        ),
        migrations.AddField(
            model_name='vyruchka',
            name='id_rabotnik',
            field=models.ForeignKey(blank=True, db_column='id_rabotnik', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rabotnik'),
        ),
        migrations.AddConstraint(
            model_name='magazintovar',
            constraint=models.UniqueConstraint(fields=('id_magazin', 'id_tovar'), name='uniq_magazin_tovar'),
        ),
    ]
