# Generated by Django 6.0 on 2025-12-14 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vyruchka_kolichestvo_magazintovar_kolichestvo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zayavki', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлена'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], default='DRAFT', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zayavki_created', to=settings.AUTH_USER_MODEL)),
                ('id_magazin', models.ForeignKey(db_column='id_magazin', on_delete=django.db.models.deletion.PROTECT, to='core.magazin')),
            ],
            options={
                'db_table': 'zayavka',
            },
        ),
        migrations.CreateModel(
            name='ZayavkaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolichestvo', models.IntegerField(blank=True, null=True)),
                ('id_tovar', models.ForeignKey(db_column='id_tovar', on_delete=django.db.models.deletion.PROTECT, to='core.tovar')),
                ('id_zayavka', models.ForeignKey(db_column='id_zayavka', on_delete=django.db.models.deletion.CASCADE, to='core.zayavka')),
            ],
            options={
                'db_table': 'zayavka_item',
                'constraints': [models.UniqueConstraint(fields=('id_zayavka', 'id_tovar'), name='uniq_zayavka_item')],
            },
        ),
    ]
