# Generated by Django 6.0 on 2025-12-16 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_zayavka_zayavkaitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavka',
            options={'permissions': [('approve_zayavka', 'Может проводить (одобрять) заявки'), ('sql_console', 'Доступ к SQL-консоли')]},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_magazin', models.ForeignKey(blank=True, db_column='id_magazin', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.magazin')),
                ('id_otdel', models.ForeignKey(blank=True, db_column='id_otdel', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.otdel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
