# Generated by Django 6.0 on 2025-12-16 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_zayavka_options_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorod',
            name='id_strana',
            field=models.ForeignKey(blank=True, db_column='id_strana', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.strana'),
        ),
        migrations.AddField(
            model_name='magazin',
            name='nomer_doma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ulitsa',
            name='id_gorod',
            field=models.ForeignKey(blank=True, db_column='id_gorod', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gorod'),
        ),
    ]
