# Generated by Django 6.0 on 2025-12-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gorod_id_strana_magazin_nomer_doma_ulitsa_id_gorod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorod',
            name='id_strana',
        ),
        migrations.RemoveField(
            model_name='ulitsa',
            name='id_gorod',
        ),
    ]
